$schema: "https://github.com/agile-learning-institute/stage0/blob/main/Schemas/product.schema.yaml"
$id: "https://github.com/justin-mike-collab/grow/blob/main/Specifications/product.yaml"
title: Product and Organization Specifications for grow

info:
  name: grow
  description: AI-reviewed Performance Reviews
  slug: grow
  developer_cli: gr
  db_name: grow_db
  base_port: 9090

organization:
  name: Justin-Mike-Collab
  email: jbarker2160@gmail.com
  founded: 1234
  slug: grow
  git_host: https://github.com
  git_org: justin-mike-collab
  docker_host: ghcr.io
  docker_org: justin-mike-collab